TARGET     =
MODE       = hrb
STACKSIZE  = 64k
MALLOCSIZE = 256k
OBJS       = $(TARGET).obj

INCPATH    = ../z_tools/haribote/
CC1OPT     =
BIMOPT0    =
BIMOPT1    = -tek5 clv:5 eopt: eprm:

include ../z_tools/hrb_mak.txt

# tolset_h‘Î‰žMakefile
